name: Deploy Labs to Server

on:
  push:
    branches:
      - main
    paths:
      - 'src/labs/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 2222 se.ifmo.ru >> ~/.ssh/known_hosts

      - name: Copy labs folder to server with password
        run: |
          sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -P 2222 -r src/labs s502499@se.ifmo.ru:~
